# Generated by Django 3.0.8 on 2020-08-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookAPI", "0002_auto_20200802_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="average_rating",
            field=models.FloatField(
                blank=True, null=True, verbose_name="average rating"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="ratings_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="rating count"
            ),
        ),
    ]
