# Generated by Django 3.0.8 on 2020-08-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPI', '0005_auto_20200806_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
    ]
