# Generated by Django 3.0.8 on 2020-08-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPI', '0006_auto_20200806_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.TextField(blank=True, null=True, verbose_name='published date'),
        ),
    ]
